// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: video.proto

package demo

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type BilliVideo struct {
	Id       string   `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Title    string   `protobuf:"bytes,2,opt,name=Title,proto3" json:"Title,omitempty"`
	PostTime int64    `protobuf:"varint,3,opt,name=PostTime,proto3" json:"PostTime,omitempty"`
	Author   string   `protobuf:"bytes,4,opt,name=Author,proto3" json:"Author,omitempty"`
	View     int32    `protobuf:"varint,5,opt,name=View,proto3" json:"View,omitempty"`
	Like     int32    `protobuf:"varint,6,opt,name=Like,proto3" json:"Like,omitempty"`
	Coin     int32    `protobuf:"varint,7,opt,name=Coin,proto3" json:"Coin,omitempty"`
	Favorite int32    `protobuf:"varint,8,opt,name=Favorite,proto3" json:"Favorite,omitempty"`
	Share    int32    `protobuf:"varint,9,opt,name=Share,proto3" json:"Share,omitempty"`
	Keywords []string `protobuf:"bytes,10,rep,name=Keywords,proto3" json:"Keywords,omitempty"`
}

func (m *BilliVideo) Reset()         { *m = BilliVideo{} }
func (m *BilliVideo) String() string { return proto.CompactTextString(m) }
func (*BilliVideo) ProtoMessage()    {}
func (*BilliVideo) Descriptor() ([]byte, []int) {
	return fileDescriptor_0ad4ea8866efb1e3, []int{0}
}
func (m *BilliVideo) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *BilliVideo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_BilliVideo.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *BilliVideo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BilliVideo.Merge(m, src)
}
func (m *BilliVideo) XXX_Size() int {
	return m.Size()
}
func (m *BilliVideo) XXX_DiscardUnknown() {
	xxx_messageInfo_BilliVideo.DiscardUnknown(m)
}

var xxx_messageInfo_BilliVideo proto.InternalMessageInfo

func (m *BilliVideo) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *BilliVideo) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *BilliVideo) GetPostTime() int64 {
	if m != nil {
		return m.PostTime
	}
	return 0
}

func (m *BilliVideo) GetAuthor() string {
	if m != nil {
		return m.Author
	}
	return ""
}

func (m *BilliVideo) GetView() int32 {
	if m != nil {
		return m.View
	}
	return 0
}

func (m *BilliVideo) GetLike() int32 {
	if m != nil {
		return m.Like
	}
	return 0
}

func (m *BilliVideo) GetCoin() int32 {
	if m != nil {
		return m.Coin
	}
	return 0
}

func (m *BilliVideo) GetFavorite() int32 {
	if m != nil {
		return m.Favorite
	}
	return 0
}

func (m *BilliVideo) GetShare() int32 {
	if m != nil {
		return m.Share
	}
	return 0
}

func (m *BilliVideo) GetKeywords() []string {
	if m != nil {
		return m.Keywords
	}
	return nil
}

func init() {
	proto.RegisterType((*BilliVideo)(nil), "demo.BilliVideo")
}

func init() { proto.RegisterFile("video.proto", fileDescriptor_0ad4ea8866efb1e3) }

var fileDescriptor_0ad4ea8866efb1e3 = []byte{
	// 243 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x3c, 0x90, 0xbf, 0x4a, 0x33, 0x41,
	0x14, 0xc5, 0x77, 0xf6, 0xdf, 0x97, 0xbd, 0x1f, 0x58, 0x0c, 0x22, 0x17, 0x8b, 0x61, 0xb1, 0xda,
	0xca, 0xc6, 0x27, 0x30, 0x82, 0x10, 0xb4, 0x90, 0x35, 0xa4, 0x8f, 0xcc, 0x85, 0x5c, 0xdc, 0x78,
	0x65, 0x32, 0x26, 0xf8, 0x16, 0x3e, 0x96, 0x65, 0x4a, 0x4b, 0xd9, 0x7d, 0x01, 0x1f, 0x41, 0x66,
	0x56, 0xb6, 0x3b, 0xbf, 0xdf, 0xe1, 0x30, 0xc3, 0x85, 0xff, 0x7b, 0xb6, 0x24, 0x97, 0xaf, 0x4e,
	0xbc, 0xe8, 0xdc, 0xd2, 0x56, 0x2e, 0x7e, 0x14, 0xc0, 0x9c, 0xbb, 0x8e, 0x57, 0xa1, 0xd2, 0x27,
	0x90, 0x2e, 0x2c, 0xaa, 0x5a, 0x35, 0x55, 0x9b, 0x2e, 0xac, 0x3e, 0x85, 0x62, 0xc9, 0xbe, 0x23,
	0x4c, 0xa3, 0x1a, 0x41, 0x9f, 0xc3, 0xec, 0x41, 0x76, 0x7e, 0xc9, 0x5b, 0xc2, 0xac, 0x56, 0x4d,
	0xd6, 0x4e, 0xac, 0xcf, 0xa0, 0xbc, 0x7e, 0xf3, 0x1b, 0x71, 0x98, 0xc7, 0xc9, 0x1f, 0x69, 0x0d,
	0xf9, 0x8a, 0xe9, 0x80, 0x45, 0xad, 0x9a, 0xa2, 0x8d, 0x39, 0xb8, 0x7b, 0x7e, 0x26, 0x2c, 0x47,
	0x17, 0x72, 0x70, 0x37, 0xc2, 0x2f, 0xf8, 0x6f, 0x74, 0x21, 0x87, 0xf7, 0x6e, 0xd7, 0x7b, 0x71,
	0xec, 0x09, 0x67, 0xd1, 0x4f, 0x1c, 0x7e, 0xf8, 0xb8, 0x59, 0x3b, 0xc2, 0x2a, 0x16, 0x23, 0x84,
	0xc5, 0x1d, 0xbd, 0x1f, 0xc4, 0xd9, 0x1d, 0x42, 0x9d, 0x35, 0x55, 0x3b, 0xf1, 0x1c, 0x3f, 0x7b,
	0xa3, 0x8e, 0xbd, 0x51, 0xdf, 0xbd, 0x51, 0x1f, 0x83, 0x49, 0x8e, 0x83, 0x49, 0xbe, 0x06, 0x93,
	0x3c, 0x95, 0xf1, 0x32, 0x57, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0xfb, 0x9b, 0x8c, 0xa8, 0x28,
	0x01, 0x00, 0x00,
}

func (m *BilliVideo) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *BilliVideo) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *BilliVideo) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Keywords) > 0 {
		for iNdEx := len(m.Keywords) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Keywords[iNdEx])
			copy(dAtA[i:], m.Keywords[iNdEx])
			i = encodeVarintVideo(dAtA, i, uint64(len(m.Keywords[iNdEx])))
			i--
			dAtA[i] = 0x52
		}
	}
	if m.Share != 0 {
		i = encodeVarintVideo(dAtA, i, uint64(m.Share))
		i--
		dAtA[i] = 0x48
	}
	if m.Favorite != 0 {
		i = encodeVarintVideo(dAtA, i, uint64(m.Favorite))
		i--
		dAtA[i] = 0x40
	}
	if m.Coin != 0 {
		i = encodeVarintVideo(dAtA, i, uint64(m.Coin))
		i--
		dAtA[i] = 0x38
	}
	if m.Like != 0 {
		i = encodeVarintVideo(dAtA, i, uint64(m.Like))
		i--
		dAtA[i] = 0x30
	}
	if m.View != 0 {
		i = encodeVarintVideo(dAtA, i, uint64(m.View))
		i--
		dAtA[i] = 0x28
	}
	if len(m.Author) > 0 {
		i -= len(m.Author)
		copy(dAtA[i:], m.Author)
		i = encodeVarintVideo(dAtA, i, uint64(len(m.Author)))
		i--
		dAtA[i] = 0x22
	}
	if m.PostTime != 0 {
		i = encodeVarintVideo(dAtA, i, uint64(m.PostTime))
		i--
		dAtA[i] = 0x18
	}
	if len(m.Title) > 0 {
		i -= len(m.Title)
		copy(dAtA[i:], m.Title)
		i = encodeVarintVideo(dAtA, i, uint64(len(m.Title)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Id) > 0 {
		i -= len(m.Id)
		copy(dAtA[i:], m.Id)
		i = encodeVarintVideo(dAtA, i, uint64(len(m.Id)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintVideo(dAtA []byte, offset int, v uint64) int {
	offset -= sovVideo(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *BilliVideo) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Id)
	if l > 0 {
		n += 1 + l + sovVideo(uint64(l))
	}
	l = len(m.Title)
	if l > 0 {
		n += 1 + l + sovVideo(uint64(l))
	}
	if m.PostTime != 0 {
		n += 1 + sovVideo(uint64(m.PostTime))
	}
	l = len(m.Author)
	if l > 0 {
		n += 1 + l + sovVideo(uint64(l))
	}
	if m.View != 0 {
		n += 1 + sovVideo(uint64(m.View))
	}
	if m.Like != 0 {
		n += 1 + sovVideo(uint64(m.Like))
	}
	if m.Coin != 0 {
		n += 1 + sovVideo(uint64(m.Coin))
	}
	if m.Favorite != 0 {
		n += 1 + sovVideo(uint64(m.Favorite))
	}
	if m.Share != 0 {
		n += 1 + sovVideo(uint64(m.Share))
	}
	if len(m.Keywords) > 0 {
		for _, s := range m.Keywords {
			l = len(s)
			n += 1 + l + sovVideo(uint64(l))
		}
	}
	return n
}

func sovVideo(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozVideo(x uint64) (n int) {
	return sovVideo(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *BilliVideo) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowVideo
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: BilliVideo: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: BilliVideo: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVideo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthVideo
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthVideo
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Id = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Title", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVideo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthVideo
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthVideo
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Title = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PostTime", wireType)
			}
			m.PostTime = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVideo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PostTime |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Author", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVideo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthVideo
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthVideo
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Author = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field View", wireType)
			}
			m.View = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVideo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.View |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Like", wireType)
			}
			m.Like = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVideo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Like |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Coin", wireType)
			}
			m.Coin = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVideo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Coin |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Favorite", wireType)
			}
			m.Favorite = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVideo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Favorite |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Share", wireType)
			}
			m.Share = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVideo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Share |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Keywords", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVideo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthVideo
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthVideo
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Keywords = append(m.Keywords, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipVideo(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthVideo
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipVideo(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowVideo
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowVideo
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowVideo
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthVideo
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupVideo
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthVideo
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthVideo        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowVideo          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupVideo = fmt.Errorf("proto: unexpected end of group")
)
